const data=[
    {
        id:'a_1',
        fullName:'Charles Banks',
        profesion:'UI Designer',
        city:'Toronto',
        country:'Canada',
        salary:30,
        workedTime:3,
        number:650,
        rate:4.5,
        rateNumber:100
    },
    {
        id:'a_2',
        fullName:'Charles Banks',
        profesion:'UI Designer',
        city:'Toronto',
        country:'Canada',
        salary:30,
        workedTime:3,
        number:650,
        rate:4.5,
        rateNumber:100
    },
    {
        id:'a_3',
        fullName:'Charles Banks',
        profesion:'UI Designer',
        city:'Toronto',
        country:'Canada',
        salary:30,
        workedTime:3,
        number:650,
        rate:4.5,
        rateNumber:100
    },
    {
        id:'a_4',
        fullName:'Charles Banks',
        profesion:'UI Designer',
        city:'Toronto',
        country:'Canada',
        salary:30,
        workedTime:3,
        number:650,
        rate:4.5,
        rateNumber:100
    },
    {
        id:'a_5',
        fullName:'Charles Banks',
        profesion:'UI Designer',
        city:'Toronto',
        country:'Canada',
        salary:30,
        workedTime:3,
        number:650,
        rate:4.5,
        rateNumber:100
    },
    {
        id:'a_6',
        fullName:'Charles Banks',
        profesion:'UI Designer',
        city:'Toronto',
        country:'Canada',
        salary:30,
        workedTime:3,
        number:650,
        rate:4.5,
        rateNumber:100
    },
    {
        id:'a_7',
        fullName:'Charles Banks',
        profesion:'UI Designer',
        city:'Toronto',
        country:'Canada',
        salary:30,
        workedTime:3,
        number:650,
        rate:4.5,
        rateNumber:100
    },
    {
        id:'a_8',
        fullName:'Charles Banks',
        profesion:'UI Designer',
        city:'Toronto',
        country:'Canada',
        salary:30,
        workedTime:3,
        number:650,
        rate:4.5,
        rateNumber:100
    },
    {
        id:'a_9',
        fullName:'Charles Banks',
        profesion:'UI Designer',
        city:'Toronto',
        country:'Canada',
        salary:30,
        workedTime:3,
        number:650,
        rate:4.5,
        rateNumber:100
    },
    {
        id:'a_10',
        fullName:'Charles Banks',
        profesion:'UI Designer',
        city:'Toronto',
        country:'Canada',
        salary:30,
        workedTime:3,
        number:650,
        rate:4.5,
        rateNumber:100
    },
    {
        id:'a_11',
        fullName:'Charles Banks',
        profesion:'UI Designer',
        city:'Toronto',
        country:'Canada',
        salary:30,
        workedTime:3,
        number:650,
        rate:4.5,
        rateNumber:100
    },
    {
        id:'a_12',
        fullName:'Charles Banks',
        profesion:'UI Designer',
        city:'Toronto',
        country:'Canada',
        salary:30,
        workedTime:3,
        number:650,
        rate:4.5,
        rateNumber:100
    },
    {
        id:'a_13',
        fullName:'Charles Banks',
        profesion:'UI Designer',
        city:'Toronto',
        country:'Canada',
        salary:30,
        workedTime:3,
        number:650,
        rate:4.5,
        rateNumber:100
    },
    {
        id:'a_14',
        fullName:'Charles Banks',
        profesion:'UI Designer',
        city:'Toronto',
        country:'Canada',
        salary:30,
        workedTime:3,
        number:650,
        rate:4.5,
        rateNumber:100
    },
    {
        id:'a_15',
        fullName:'Charles Banks',
        profesion:'UI Designer',
        city:'Toronto',
        country:'Canada',
        salary:30,
        workedTime:3,
        number:650,
        rate:4.5,
        rateNumber:100
    },
    {
        id:'a_16',
        fullName:'Charles Banks',
        profesion:'UI Designer',
        city:'Toronto',
        country:'Canada',
        salary:30,
        workedTime:3,
        number:650,
        rate:4.5,
        rateNumber:100
    },
    {
        id:'a_17',
        fullName:'Charles Banks',
        profesion:'UI Designer',
        city:'Toronto',
        country:'Canada',
        salary:30,
        workedTime:3,
        number:650,
        rate:4.5,
        rateNumber:100
    },
    {
        id:'a_18',
        fullName:'Charles Banks',
        profesion:'UI Designer',
        city:'Toronto',
        country:'Canada',
        salary:30,
        workedTime:3,
        number:650,
        rate:4.5,
        rateNumber:100
    },
    {
        id:'a_19',
        fullName:'Charles Banks',
        profesion:'UI Designer',
        city:'Toronto',
        country:'Canada',
        salary:30,
        workedTime:3,
        number:650,
        rate:4.5,
        rateNumber:100
    },
    {
        id:'a_20',
        fullName:'Charles Banks',
        profesion:'UI Designer',
        city:'Toronto',
        country:'Canada',
        salary:30,
        workedTime:3,
        number:650,
        rate:4.5,
        rateNumber:100
    },
];




export default data;